services:
  db:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_USER: mingde
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
