server:
  port: ":8080"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "<db-password>"
  dbname: "blog_db"
  sslmode: "disable"

r2:
  account_id: "<cloudflare-account-id>"
  access_key_id: "<r2-access-key-id>"
  secret_access_key: "<r2-secret-access-key>"
  bucket_name: "<r2-bucket-name>"
  public_domain: "https://example.com"

auth:
  jwt_secret: "<strong-random-secret-at-least-32-chars>"
  initial_admin_username: ""
  initial_admin_email: ""
  initial_admin_password: ""
